[window] 
padding = { x = 10 , y = 5}
opacity = 0.9

[font]
normal = { family = "Fira Code", style = "Light" }
bold = { family = "Fira Code", style = "Bold" }
size = 11

#Offset - ExtraSpace around each character
offset = {x =1, y = 0}

[cursor]
style = { shape = "Underline", blinking = "On" }

